# Generated by Django 5.2.3 on 2025-06-14 07:53

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('end_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('current_position', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plane', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pilot', to='fleet.plane')),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('accepted', 'Kabul Edildi'), ('rejected', 'Reddedildi')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='fleet.plane')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
