# Generated by Django 5.2.3 on 2025-06-14 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pilot',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='pilot',
            name='plane',
        ),
        migrations.AddField(
            model_name='plane',
            name='pilot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plane', to='fleet.pilot'),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
