# Generated by Django 5.2.3 on 2025-06-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_alter_pilot_options_remove_pilot_plane_plane_pilot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plane',
            name='is_going_to_end',
            field=models.BooleanField(default=True),
        ),
    ]
